name: Code testing

on:
  push:
    branches:
      - main
      - Dev
      - feature*
  pull_request:
    branches:
      - main
      - Dev

jobs:
  tests:
    name: Unit and Functional Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
  
      - name: Install dependencies
        run: |
          pip install pytest

      - name: Unit Tests
        run: |
          pytest tests/unit/*

      - name: Functional Tests
        run: |
          pytest tests/functional/*

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml